apiVersion: apps/v1
kind: DaemonSet
metadata: # kpt-merge: /pipewire
  name: pipewire # kpt-set: ${name}
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|DaemonSet|default|pipewire'
spec:
  template:
    spec:
      containers:
      - name: pipewire
        envFrom:
        - secretRef:
            name: ${APP_NAME:=app}-defaultconfig
        - secretRef:
            name: ${APP_CONFIG_SECRET_NAME:=app-defaultconfig}
