apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pipewire # kpt-set: ${name}
spec:
  template:
    spec:
      containers:
      - name: pipewire
        envFrom:
        - secretRef:
            name: ${APP_NAME:=app}-defaultconfig
        - secretRef:
            name: ${APP_CONFIG_SECRET_NAME:=app-defaultconfig}
